language: node.js
node_js:
  - 8

before_script:
  - npm install
  - npm run lint

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run test
  - npm run coveralls
  - npm run build
